.\" Manpage for decaby7e.
.\" Contact me at decaby7e@ranvier.net

.TH Jack Polk 8 "Jul 2001" "1.0" "Jack's man page"

.SH NAME

Jack Polk \- Computer Science major at the University of Florida with a passion for Linux, web development, cybersecurity,
self-hosting, CI/CD, DevOps, and much more!

.SH SYNOPSIS

decaby7e [USERNAME]

.SH DESCRIPTION

A computer scientist by night and climber by day!

.SH OPTIONS

-c/--caffeine - Boosts performance by 100%

-v/--verbose - Increases verbosity. (WARNING: levels past 4 may result in sporadic deep philosophical conversations that never end)

.SH BUGS

- Is perfectionist

- FOSS lover

- Self-hosts 90% of software and services

- Can't handle people who are clueless

.SH SEE ALSO

ranvier.net, cise.ufl.edu/~jfp, www.linkedin.com/in/jack-polk-69b193147

.SH AUTHOR

Jack Polk (decaby7e@ranvier.net)
