.\" Manpage for decaby7e.
.\" Contact me at decaby7e@ranvier.net

.TH decaby7e 8 "06 Jul 2001" "1.0" "decaby7e man page"

.SH NAME
decaby7e \- System administrator with a passion for Linux systems, web development, and blue team security

.SH SYNOPSIS
decaby7e [USERNAME]

.SH DESCRIPTION
This description is under construction

.SH OPTIONS
My options are under construction

.SH SEE ALSO
www.ranvier.net, cise.ufl.edu/~jfp/, www.linkedin.com/in/jack-polk-69b193147/

.SH BUGS

- Has an obsession with perfectionism

- Loves FOSS software and tries very hard to avoid proprietary solutions

- Doesn't tolerate incompetence

.SH AUTHOR
Jack Polk (decaby7e@ranvier.net)
